config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);
Router::scope('/', function (RouteBuilder $routes) {

    $routes->connect('/', ['controller' => 'Users', 'action' => 'login']);


    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    $routes->connect('/applications', ['controller' => 'Applications', 'action' => 'index']);

    $routes->connect('/communications', ['controller' => 'Communications', 'action' => 'index']);

	// New route we're adding for our tagged action
	// The trailing '*' tells CakePHP that this action has 
	// passed parameter

	// Router::scope('/applications',['controller' => 'Bookmarks', 'action' => 'index']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);

    // Connects the conventios based default routes.
    $routes->fallbacks();
});

src/Model/Entity/Communication.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Communication Entity
 *
 * @property int $id
 * @property bool $commtype
 * @property string $author
 * @property \Cake\I18n\FrozenDate $start_date
 * @property \Cake\I18n\FrozenDate $stop_date
 * @property string $heading
 * @property string $message
 * @property \Cake\I18n\FrozenTime $created
 * @property \Cake\I18n\FrozenTime $modified
 */
class Communication extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        // 'communication_type' => true,
        'author' => true,
        'start_date' => true,
        'stop_date' => true,
        'heading' => true,
        'message' => true,
        'application' => true,
        'company' => true,
        'status' => true,
        'created' => true,
        'modified' => true
    ];
}

src/Model/Table/CommunicationsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Communications Model
 *
 * @method \App\Model\Entity\Communication get($primaryKey, $options = [])
 * @method \App\Model\Entity\Communication newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Communication[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Communication|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Communication|bool saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Communication patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Communication[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Communication findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class CommunicationsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('communications');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

		$this->belongsTo('Comments', [
			'foreignKey' => 'id',
			'joinType' => 'INNER'
		]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        // $validator
        //     ->boolean('communication_type')
        //     ->requirePresence('communication_type', 'create')
        //     ->notEmpty('communication_type');

        $validator
            ->scalar('author')
            ->maxLength('author', 500)
            ->requirePresence('author', 'create')
            ->notEmpty('author');

        $validator
            ->date('start_date')
            ->requirePresence('start_date', 'create')
            ->notEmpty('start_date');

        $validator
            ->date('stop_date')
            ->allowEmpty('stop_date');

        $validator
            ->scalar('heading')
            ->maxLength('heading', 500)
            ->requirePresence('heading', 'create')
            ->notEmpty('heading');

        $validator
            ->scalar('message')
            ->requirePresence('message', 'create')
            ->notEmpty('message');

        $validator
            ->integer('application')
            ->notEmpty('application','create');

         $validator
            ->integer('company')
            ->notEmpty('company','create');

        $validator
            ->integer('status')
            ->allowEmpty('status');

        return $validator;
    }
}

src/Controller/CommunicationsController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;

class CommunicationsController extends AppController
{

	public function initialize(){
		parent::initialize();
        $this->Auth->allow([
            'index',
            'lists',
            'view',
            'add',
            'edit',
            'delete',
            'archived',
            'postcomment',
            'getcomment',
            'toarchived',
            'usercomments',
            'userlikes',
            'likecomment',
            'updatestatus',
            'acknowledge',
        ]);
		$this->viewBuilder()->setLayout('home');
		$this->loadComponent('RequestHandler');
	}

    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event);
        $this->Auth->allow([
            'postcomment',
            'getcomment',
            'likecomment',
            'getusercomment',
            'getcommentlikecount',
            'getuserlike',
            'getcommentusercount'
        ]);
        $actions = [
            'postcomment',
            'getcomment',
            'likecomment',
            'getusercomment',
            'getcommentlikecount',
            'getuserlike',
            'getcommentusercount'
        ];

        if (in_array($this->request->getParam('action'), $actions)) {
            $this->eventManager()->off($this->Csrf);
            $this->Security->config('unlockedActions', $actions);
        }
    }
    
	public function index(){}

	public function add()
	{
		$communication = $this->Communications->newEntity();
		if ($this->request->is('post')) {
			$communication = $this->Communications->patchEntity($communication, $this->request->getData());
			if ($this->Communications->save($communication)) {
				$this->autoRender = false;
				echo json_encode(['result' => 'success', 'communication_data' => $this->request->getData()]);
			} else {
				echo json_encode(['result' => 'error']);
			}
		}
		$this->set(compact('communication'));
	}

    public function edit($id = null, $app_id = null)
    {
        $communication = $this->Communications->get($id);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $communication = $this->Communications->patchEntity($communication, $this->request->getData());
            if ($this->Communications->save($communication)) {
                $this->autoRender = false;
                echo json_encode(['result' => 'success', 'communication_data' => $this->request->getData()]);
            } else {
                echo json_encode(['result' => 'error']);
            }
        }
        $this->set(compact('communication','app_id'));
    }

    public function delete($id = null, $app_id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $communication = $this->Communications->get($id);
        if ($this->Communications->delete($communication)) {
            $this->Flash->success(__('Successfully removed.'));
        } else {
            $this->Flash->error(__('The communication could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'lists', $app_id]);
    }

	public function lists($id = null) 
    {
        $communication = $this->Communications->newEntity();
        if ($this->request->is('post')) {
            $communication = $this->Communications->patchEntity($communication, $this->request->getData());
            if ($this->Communications->save($communication)) {
                $this->autoRender = false;
                echo json_encode(['result' => 'success', 'communication_data' => $this->request->getData()]);
            } else {
                echo json_encode(['result' => 'error']);
            }
        }
		$communicationlist = $this->Communications->find()->where(['application' => $id, 'company' => $this->Auth->user('company')]);
		$this->set(compact('communicationlist','id','communication'));
	}

	public function archived($id = null) 
    {
		$communicationlist = $this->Communications->find()->where(['status' => 3, 'application' => $id, 'company' => $this->Auth->user('company')]);
		$this->set(compact('communicationlist','id'));
	}

	public function postcomment() 
	{
		$this->autoRender = false;
		$comments = $this->Comments->newEntity();
		if ( $this->request->is('ajax') && $this->request->is('post')) {
			$comments = $this->Comments->patchEntity($comments, $this->request->getData());
			if ($this->Comments->save($comments)) {
				echo json_encode(['result' => 'success', 'comments_data' => $this->request->getData()]);
			} else {
				echo json_encode(['result' => 'error']);
			}
		}
	}

	public function likecomment() 
	{
		$this->autoRender = false;
		$likes = $this->Likes->newEntity();
		$likeTable = TableRegistry::get('Likes');
		$exist = $likeTable->find()->where(['users' => $this->request->getData('users'), 'communication_id' => $this->request->getData('communication_id')])->count();
		if($exist > 0) {
			$removedExist = $likeTable->query()->delete()->where(['users' => $this->request->getData('users'), 'communication_id' => $this->request->getData('communication_id')])->execute();
			if ($removedExist) {
				echo json_encode(['result' => 'remove_exist']);
			}
		} else {
			if ( $this->request->is('ajax') && $this->request->is('post')) {
				$likes = $this->Likes->patchEntity($likes, $this->request->getData());
				if ($this->Likes->save($likes)) {
					echo json_encode(['result' => 'success', 'likes_data' => $this->request->getData()]);
				} else {
					echo json_encode(['result' => 'error']);
				}
			}
		}
	}


	public function getcomment() 
	{
		$this->autoRender = false;
		if ( $this->request->is('ajax') && $this->request->is('post')) {
			$data = $this->request->getData();
			$comments = $this->Comments->find('all')->contain(['Users'])->where(['communication_id' => $data['communication_id']])->order(['post_date' => 'DESC']);
			echo json_encode(['comments_data' => $comments]);
		}
	}

	public function getusercomment() 
	{
		$this->autoRender = false;
		if ( $this->request->is('ajax') && $this->request->is('post')) {
			$data = $this->request->getData();
			$comments = $this->Comments->find('all')->contain(['Users'])->where(['communication_id' => $data['communication_id']])->order(['post_date' => 'DESC'])->group(['users']);
			echo json_encode(['comments_data' => $comments]);
		}
	}

	public function getuserlike() 
	{
		$this->autoRender = false;
		if ( $this->request->is('ajax') && $this->request->is('post')) {
			$data = $this->request->getData();
			$likes = $this->Likes->find('all')->contain(['Users'])->where(['communication_id' => $data['communication_id']])->order(['date_post' => 'DESC'])->group(['users']);
			echo json_encode(['user_like_data' => $likes]);
		}
	}

	public function usercomments($id = null, $list_id = null)
	{
		$usercomments = $this->Comments->find('all')->contain(['Users'])->where(['communication_id' => $id])->order(['post_date' => 'DESC']);
		$this->set(compact('usercomments','id','list_id'));
	}

	public function userlikes($id = null, $list_id = null)
	{
		$userlikes = $this->Likes->find('all')->contain(['Users'])->where(['communication_id' => $id])->order(['date_post' => 'DESC']);
		$this->set(compact('userlikes','id','list_id'));
	}

	public function getcommentlikecount($id = null) {
		$this->autoRender = false;
		$query = $this->Likes->find()->where(['communication_id' => $id])->count();
		echo json_encode(['count' => $query]);
	}

	public function getcommentusercount($id = null) {
		$this->autoRender = false;
		$query = $this->Comments->find()->where(['communication_id' => $id]);
		echo json_encode(['count' => $query->count()]);
	}

    public function toarchived($id = null, $app_id = null)
    {
        $this->autoRender = false;
        $communicationTable = TableRegistry::get('Communications');
        $communication = $communicationTable->get($id);

        $communication->status = 3;
        $communicationTable->save($communication);
        $this->Flash->success(__('Successfully move to archived.'));
        return $this->redirect(['action' => 'lists', $app_id]);
    }

    public function updatestatus($id = null, $status = null, $app_id = null)
    {
        $commsTable = TableRegistry::get('Communications');
        $comms = $commsTable->get($id);
        $comms->status = $status;
        if($commsTable->save($comms)) {
            $this->Flash->success(__('Updated Status.'));
            return $this->redirect(['action' => 'lists',$app_id]);
        }
    }

	public function acknowledge($id = null, $app_id = null)
	{
		$acknowledges = $this->Acknowledges->find('all')->contain(['Users'])->where(['communication_id' => $id])->toArray();
		$this->set(compact('acknowledges','app_id'));
	}

    public function modaldata() {
		$this->autoRender = false ;   
		$data = $this->request->getData();
		$communication = $this->Communications->get($data['id']);
		$json_data = json_encode(
			array(
				'communication' => $communication,
				'request' => isset($data['title'])? $data['title'] : ''
			)
		);
		$response = $this->response->withType('json')->withStringBody($json_data);
		return $response;
    }
}

src/Template/Communications/acknowledge.ctp
<div class="card">
	<div class="card-body">
		<h3  class="card-title"><b>User Acknowledge</b></h3>
		<div class="p5">
		<?php
			echo $this->Html->link(
				'<i class="fa fa-undo"></i> Back',
			[
				'controller' => 'Communications',
				'action' => 'lists',
				$app_id
			],
			[ 
				'escape' => false,
				'class' => 'btn btn-warning'
			]
			)
		?>
		</div>
		<div class="table-responsive">
			<table id="userCommentsTable" class="table table-bordered">
				<thead>
					<tr>
						<th>Name</th>
						<th>Acknowledge Date</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($acknowledges as $acknowledge): ?>
						<tr>
							<td><?= h($acknowledge->user['firstname']).' '.h($acknowledge->user['lastname']) ?></td>
							<td><?= h($acknowledge->created) ?></td>
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</div>

src/Template/Communications/apps.ctp
<div class="row">
	<!-- Column -->
	<div class="col-md-6 col-lg-2 col-xlg-3">
	    <div class="card card-hover">
	        <div class="box bg-cyan text-center">
	            <h1 class="font-light text-white"><i class="mdi mdi-view-dashboard"></i></h1>
	            <h6 class="text-white">Dashboard</h6>
	        </div>
	    </div>
	</div>
	 <!-- Column -->
	<div class="col-md-6 col-lg-2 col-xlg-3">
	    <div class="card card-hover">
	        <div class="box bg-warning text-center">
	            <h1 class="font-light text-white"><i class="mdi mdi-collage"></i></h1>
	            <h6 class="text-white">Widgets</h6>
	        </div>
	    </div>
	</div>
	<!-- Column -->
	<div class="col-md-6 col-lg-2 col-xlg-3">
	    <div class="card card-hover">
	        <div class="box bg-danger text-center">
	            <h1 class="font-light text-white"><i class="mdi mdi-border-outside"></i></h1>
	            <h6 class="text-white">test</h6>
	        </div>
	    </div>
	</div>
	<!-- Column -->
	<div class="col-md-6 col-lg-2 col-xlg-3">
	    <div class="card card-hover">
	        <div class="box bg-info text-center">
	            <h1 class="font-light text-white"><i class="mdi mdi-arrow-all"></i></h1>
	            <h6 class="text-white">Full Width</h6>
	        </div>
	    </div>
	</div>
	<!-- Column -->
	<div class="col-md-6 col-lg-2 col-xlg-3">
	    <div class="card card-hover">
	        <div class="box bg-info text-center">
	            <h1 class="font-light text-white"><i class="mdi mdi-relative-scale"></i></h1>
	            <h6 class="text-white">Buttons</h6>
	        </div>
	    </div>
	</div>
	 <!-- Column -->
	<div class="col-md-6 col-lg-2 col-xlg-3">
	    <div class="card card-hover">
	        <div class="box bg-cyan text-center">
	            <h1 class="font-light text-white"><i class="mdi mdi-pencil"></i></h1>
	            <h6 class="text-white">Elements</h6>
	        </div>
	    </div>
	</div>
	<!-- Column -->
	<div class="col-md-6 col-lg-2 col-xlg-3">
	    <div class="card card-hover">
	        <div class="box bg-success text-center">
	            <h1 class="font-light text-white"><i class="mdi mdi-calendar-check"></i></h1>
	            <h6 class="text-white">Calnedar</h6>
	        </div>
	    </div>
	</div>
	<!-- Column -->
	<div class="col-md-6 col-lg-2 col-xlg-3">
	    <div class="card card-hover">
	        <div class="box bg-warning text-center">
	            <h1 class="font-light text-white"><i class="mdi mdi-alert"></i></h1>
	            <h6 class="text-white">Errors</h6>
	        </div>
	    </div>
	</div>
	<!-- Column -->
</div>

src/Template/Communications/archived.ctp
<div class="card">
	<div class="card-body">
		<h3 class="card-title"><b>Archived List</b></h3>
		<div class="table-responsive">
			<div class="p5 l10">
				<?php
					echo $this->Html->link(
						'<i class="fa fa-undo"></i> List',
						[
							'controller' => 'Communications',
							'action' => 'lists',
							$id
						],
						[ 
							'escape' => false,
							'class' => 'btn btn-primary btn-sm'
						]
					)
				?>
			</div>
			<table id="communication_table" class="table table-bordered">
				<thead>
					<tr>
						<th>Title</th>
						<th>Author</th>
						<th>Release</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($communicationlist as $communication): ?>
					<tr style="<?= h($communication->status == 1)? 'font-weight: bold' : ''; ?>">
						<td><?= ucfirst(h($communication->author)) ?></td>
						<td><?= ucfirst(h($communication->heading)) ?></td>
						<td><?= h($communication->created) ?></td>
						<td class="actions">
							<?= $this->Html->link(__('<i class="fas fa-undo"></i>  Active'), ['action' => 'edit', $communication->id, $id], ['class' => 'btn btn-sm btn-info', 'escape' => false]) ?>
							<?= $this->Form->postLink(__('<i class="fa fa-trash"></i> Remove Completely'), ['action' => 'delete', $communication->id, $id], ['confirm' => __('Are you sure you want to remove this completely?', $communication->id), 'escape' => false, 'class' => 'btn btn-sm btn-danger']) ?>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel"><span id="view_title"></span></h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<p class="loadingAnimated" id="view_content"></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

src/Template/Communications/edit.ctp
<div class="card">
	<?= $this->Form->create($communication, ['class' => 'form-horizontal']) ?>
	<div class="card-body">
		<h4 class="card-title">Edit Communication</h4>
		<?= $this->Form->control('author', ['placeholder' => 'Complete Name', 'class' => 'form-control', 'label' => 'Author']) ?>
		<?= $this->Form->control('start_date', ['class' => 'form-control', 'type' => 'text', 'value' => date('Y-m-d'), 'label' => 'Start Date']) ?>
		<?= $this->Form->control('stop_date', ['class' => 'form-control', 'type' => 'text', 'label' => 'Stop Date']) ?>
		<?=  $this->Form->control('heading', ['class' => 'form-control', 'label' => 'Title']) ?>
		<?= $this->Form->control('message', ['type' => 'textarea','class' => 'form-control']) ?>
		<div style="display: none;">
			<?=  $this->Form->control('status', ['type' => 'text']) ?>
		</div>
	</div>
	<div class="border-top">
		<div class="card-body">
			<?= $this->Form->button(__('<i class="fa fa-save"></i> Save & Exit'), ['class' => 'btn btn-primary','name' => 'save', 'escape' => false]) ?>
			<?php
				echo $this->Html->link(
					'<i class="fa fa-times"></i> Cancel',
				[
					'controller' => 'Communications',
					'action' => 'lists',
					$app_id
				],
				[ 
					'escape' => false,
					'class' => 'btn btn-danger btn-md'
				]
				)
			?>
			<?= $this->Form->button(__('<i class="fa fa-check"></i> Publish'), ['class' => 'btn btn-primary', 'name' => 'publish', 'escape' => false]) ?>
		</div>
	</div>
	<?php
	$link = $_SERVER['REQUEST_URI'];
	$link_array = explode('/',$link);
	$lastUri = end($link_array);
	?>
	<?= $this->Form->end() ?>
</div>
<?= $this->Html->script(['libs/jquery/dist/jquery.min']) ?>
<script type="text/javascript">
	$(function () {
		$("button[name='save']").on('click', function() {
			$("#status").val('1');
		});
		$("button[name='publish']").on('click', function() {
			$("#status").val('2');
		});
		$("form").on("submit", function( event) {
			event.preventDefault();
			$.ajax({
				type: 'post',
				async: true,
				cache: false,
				url:'<?= $lastUri ?>',
				success: function (response) {
					var pj = $.parseJSON(response);
					if(pj.result == "success") {
						toastr.success('Updated communication succesfully.','Success');
						$("#status").val('');
						window.setTimeout( function () {
							window.location.href = '<?=BASE_URL?>communications/lists/<?= $app_id ?>';
						}, 3000);
					} else {
						toastr.error('Something error in updating communication.', 'Error!');
					}
				},
				error: function(response) {
					toastr.error('Something error in updating communication.', 'Error!');
				},
				data: $("form").serialize()
			});
		});
	});
</script>

src/Template/Communications/usercomments.ctp
<div class="card">
	<div class="card-body">
		<h3  class="card-title"><b>Acknowledge</b></h3>
		<div class="p5">
		<?php
			echo $this->Html->link(
				'<i class="fa fa-undo"></i> Back',
			[
				'controller' => 'Communications',
				'action' => 'lists',
				$list_id
			],
			[ 
				'escape' => false,
				'class' => 'btn btn-warning'
			]
			)
		?>
		</div>
		<div class="table-responsive">
			<table id="userCommentsTable" class="table table-bordered">
				<thead>
					<tr>
						<th>Username</th>
						<th>Comment</th>
						<th>Commented Date & Time</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($usercomments as $usercomment): ?>
						<tr>
							<td><?= h($usercomment->user['firstname']).' '.h($usercomment->user['lastname']) ?></td>
							<td><?= h($usercomment->comment) ?></td>
							<td><?= h($usercomment->created) ?></td>
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</div>

src/Template/Communications/userlikes.ctp
<div class="card">
	<div class="card-body">
		<h3  class="card-title"><b>User Likes Management</b></h3>
		<div class="p5">
		<?php
			echo $this->Html->link(
				'<i class="fa fa-undo"></i> Back',
			[
				'controller' => 'Communications',
				'action' => 'lists',
				$list_id
			],
			[ 
				'escape' => false,
				'class' => 'btn btn-warning'
			]
			)
		?>
		</div>
		<div class="table-responsive">
			<table id="userCommentsTable" class="table table-bordered">
				<thead>
					<tr>
						<th>Username</th>
						<th>Like Date & Time</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($userlikes as $userlike): ?>
						<tr>
							<td><?= h($userlike->user['firstname']).' '.h($userlike->user['lastname']) ?></td>
							<td><?= h($userlike->created) ?></td>
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</div>

src/Template/Communications/view.ctp
<div class="card">
	<div class="card-body">
		<?= $this->Html->link(__('Edit'), ['action' => 'edit', $communication->id], ['class' => 'btn btn-primary']) ?>
		<?= $this->Html->link(__('New Communication'), ['action' => 'add'], ['class' => 'btn btn-primary']) ?>
		<?= $this->Html->link(__('List Communications'), ['action' => 'communicationlist'], ['class' => 'btn btn-info']) ?>
		<?= $this->Form->postLink(
			__('Delete'),
			['action' => 'delete', $communication->id],
			['confirm' => __('Are you sure you want to delete # {0}?', $communication->id), 'class' => 'btn btn-danger']
		)
		?>
	</div>
		<div class="card-body">
			<h4 class="card-title">View Communication</h4>
			<div class="form-group row">
				<label for="fname" class="col-sm-3 text-right control-label col-form-label">Communication Type</label>
				<div class="col-sm-9">
					<?php
						if($communication->communication_type == 0) {
							echo 'General Communication';
						} else {
							echo 'Critical Communication';
						}
					?>
				</div>
			</div>
			<div class="form-group row">
				<label for="lname" class="col-sm-3 text-right control-label col-form-label">Author</label>
				<div class="col-sm-9"><?= h($communication->author) ?></div>
			</div>
			<div class="form-group row">
				<label for="lname" class="col-sm-3 text-right control-label col-form-label">Start Date</label>
				<div class="col-sm-9"><?= h($communication->start_date) ?></div>
			</div>
			<div class="form-group row">
				<label for="lname" class="col-sm-3 text-right control-label col-form-label">Stop Date</label>
				<div class="col-sm-9"><?= h($communication->stop_date) ?></div>
			</div>
			<div class="form-group row">
				<label for="cono1" class="col-sm-3 text-right control-label col-form-label">Heading</label>
				<div class="col-sm-9"><?= h($communication->heading) ?></div>
			</div>
			<div class="form-group row">
				<label for="cono1" class="col-sm-3 text-right control-label col-form-label">Message</label>
				<div class="col-sm-9"><?= $this->Text->autoParagraph(h($communication->message)); ?></div>
			</div>
		</div>
</div>